version: '3'

networks:
  concourse-network:
    driver: overlay
  traefik-network:
    external: true

services:
  concourse-db:
    image: postgres:9
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    networks: 
      - concourse-network
  concourse-web:
    image: concourse/concourse
    command: web
    depends_on: [concourse-db]
    volumes: ["./keys/web:/concourse-keys"]
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.network=concourse-network"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${CONCOURSE_EXTERNAL_URL}"
    networks:
      - traefik-network
      - concourse-network
    ports: 
      - "8888:8080" # need to be published until it can be run as swarm stack...
    privileged: true
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "${CONCOURSE_EXTERNAL_URL}"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: changeme
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse
    privileged: true
    networks:
      - concourse-network
    depends_on: [concourse-web]
    command: worker
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
